### ISSUE TITLE
Composed query should be improved

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/FamixQueries#12]
Maybe it should be renamed SavedQuery.
storeOn: method is complicated: how to clearly state all parents/children relationships in a string ?

As composed queries are meant to be saved, maybe they should always have a specific name and be registered in library when created.
The storeOn: string would then just be a call to the library with this name (and not a complex unreadable string).

**Comment by jordanmontt** [comment]
We removed this query so I am going to close this issue :)
