### ISSUE TITLE
Make saved queries configurable

### ISSUE THREAD

**Issue by ClotildeToullec** [moosetechnology/FamixQueries#13]
When constructing a query made of other queries, make it possible to specify some configurable parameters.

Example: a query composed of: 
- a type query (Classes)
- a Numeric query (#numberOfMethods > 20)

We may want to change the numeric value depending on the context. Not the other parameters (Classes, #numberOfMethods, #>)

**Comment by jordanmontt** [comment]
We removed this query (composed query) so I am going to close this issue :)
