### ISSUE TITLE
Remove query and subquery

### ISSUE THREAD

**Issue by NicolasAnquetil** [moosetechnology/FamixQueries#35]
When a query has a subquery (child) and we remove the parent query, then its child query becomes child of another query.

When deleting a query with a subquery, we should probably also remove the subquery, or make the subquery a top one, but not attach it to a random other query

**Comment by jordanmontt** [comment]
Are you talking about the queries browser or FamixQueries?  Because in the queries browser when you delete a query it also removes all its children.
Can you provide me a code snipped to reproduce this please? @NicolasAnquetil

**Comment by jordanmontt** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/33934979/128849302-00ad3ab7-0d36-48bc-b0cd-3e982dbc03d6.gif)

All the subqueries are deleted

**Comment by NicolasAnquetil** [comment]
OK, linked to #33 
the subquery is not removed because it actually belongs to another parent but it is displayed at the wrong place
